#!/bin/sh

# 1. Resolve symlinks (Crucial for Homebrew)
PRG="$0"
while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# 2. Get the actual directory of this script (the 'bin' folder in the Cellar)
DIR=$(dirname "$PRG")

# 3. Execute the Jar using your custom JRE
exec "$DIR/../jre/bin/java" -jar "$DIR/../lib/sprout.jar" "$@"